debug: true
spring:
  datasource:
    generate-unique-name: false
    name: springplayground
  jpa:
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: true
  data:
    rest:
      base-path: /data-rest-api
  rsocket:
    server:
      port: 7000